import type { ElementStandardMetaEntry } from '../../../standard/meta/entry/type.js'
import type { ElementStandardNonVoidTagName } from '../tagName/type.js'

export const elementStandardNonVoidMeta: Record<
  ElementStandardNonVoidTagName,
  ElementStandardMetaEntry
> = {
  ...{
    a: { ariaRoles: ['link'], status: 'living-standard' },
    abbr: { ariaRoles: [], status: 'living-standard' },
    acronym: { ariaRoles: [], status: 'deprecated' },
    address: { ariaRoles: ['group'], status: 'living-standard' },
    article: { ariaRoles: ['article'], status: 'living-standard' },
    aside: { ariaRoles: ['complementary'], status: 'living-standard' },
    audio: { ariaRoles: [], status: 'living-standard' },
    b: { ariaRoles: ['generic'], status: 'living-standard' },
    bdi: { ariaRoles: ['generic'], status: 'living-standard' },
    bdo: { ariaRoles: ['generic'], status: 'living-standard' },
    big: { ariaRoles: ['generic'], status: 'deprecated' },
    blockquote: { ariaRoles: ['blockquote'], status: 'living-standard' },
    body: { ariaRoles: ['generic'], status: 'living-standard' },
    button: { ariaRoles: ['button'], status: 'living-standard' },
    canvas: { ariaRoles: [], status: 'living-standard' },
    caption: { ariaRoles: ['caption'], status: 'living-standard' },
    center: { ariaRoles: ['generic'], status: 'deprecated' },
    cite: { ariaRoles: [], status: 'living-standard' },
    code: { ariaRoles: ['code'], status: 'living-standard' },
    colgroup: { ariaRoles: [], status: 'living-standard' },
    data: { ariaRoles: ['generic'], status: 'living-standard' },
    datalist: { ariaRoles: ['listbox'], status: 'living-standard' },
    dd: { ariaRoles: [], status: 'living-standard' },
    del: { ariaRoles: ['deletion'], status: 'living-standard' },
    details: { ariaRoles: ['group'], status: 'living-standard' },
    dfn: { ariaRoles: ['term'], status: 'living-standard' },
    dialog: { ariaRoles: ['dialog'], status: 'living-standard' },
    dir: { ariaRoles: ['list'], status: 'deprecated' },
    div: { ariaRoles: ['generic'], status: 'living-standard' },
    dl: { ariaRoles: [], status: 'living-standard' },
    dt: { ariaRoles: ['term'], status: 'living-standard' },
    em: { ariaRoles: ['emphasis'], status: 'living-standard' },
    fieldset: { ariaRoles: ['group'], status: 'living-standard' },
    figcaption: { ariaRoles: [], status: 'living-standard' },
    figure: { ariaRoles: ['figure'], status: 'living-standard' },
    font: { ariaRoles: ['generic'], status: 'deprecated' },
    footer: {
      ariaRoles: ['contentinfo', 'generic'],
      status: 'living-standard',
    },
    form: { ariaRoles: ['form'], status: 'living-standard' },
    frame: { ariaRoles: [], status: 'deprecated' },
    frameset: { ariaRoles: [], status: 'deprecated' },
    h1: { ariaRoles: ['heading'], status: 'living-standard' },
    h2: { ariaRoles: ['heading'], status: 'living-standard' },
    h3: { ariaRoles: ['heading'], status: 'living-standard' },
    h4: { ariaRoles: ['heading'], status: 'living-standard' },
    h5: { ariaRoles: ['heading'], status: 'living-standard' },
    h6: { ariaRoles: ['heading'], status: 'living-standard' },
    head: { ariaRoles: [], status: 'living-standard' },
    header: { ariaRoles: ['banner', 'generic'], status: 'living-standard' },
    hgroup: { ariaRoles: ['group'], status: 'living-standard' },
    html: { ariaRoles: ['document'], status: 'living-standard' },
    i: { ariaRoles: ['generic'], status: 'living-standard' },
    iframe: { ariaRoles: [], status: 'living-standard' },
    ins: { ariaRoles: ['insertion'], status: 'living-standard' },
    kbd: { ariaRoles: [], status: 'living-standard' },
    label: { ariaRoles: [], status: 'living-standard' },
    legend: { ariaRoles: [], status: 'living-standard' },
    li: { ariaRoles: ['listitem'], status: 'living-standard' },
    main: { ariaRoles: ['main'], status: 'living-standard' },
    map: { ariaRoles: [], status: 'living-standard' },
    mark: { ariaRoles: ['mark'], status: 'living-standard' },
    marquee: { ariaRoles: ['marquee'], status: 'deprecated' },
    menu: { ariaRoles: ['list'], status: 'living-standard' },
    meter: { ariaRoles: ['meter'], status: 'living-standard' },
    nav: { ariaRoles: ['navigation'], status: 'living-standard' },
    nobr: { ariaRoles: [], status: 'deprecated' },
    noembed: { ariaRoles: [], status: 'deprecated' },
    noframes: { ariaRoles: [], status: 'deprecated' },
    noscript: { ariaRoles: [], status: 'living-standard' },
    object: { ariaRoles: [], status: 'living-standard' },
    ol: { ariaRoles: ['list'], status: 'living-standard' },
    optgroup: { ariaRoles: ['group'], status: 'living-standard' },
    option: { ariaRoles: ['option'], status: 'living-standard' },
    output: { ariaRoles: ['status'], status: 'living-standard' },
    p: { ariaRoles: ['paragraph'], status: 'living-standard' },
    picture: { ariaRoles: [], status: 'living-standard' },
    plaintext: { ariaRoles: [], status: 'deprecated' },
    pre: { ariaRoles: ['generic'], status: 'living-standard' },
    progress: { ariaRoles: ['progressbar'], status: 'living-standard' },
    q: { ariaRoles: ['generic'], status: 'living-standard' },
    rb: { ariaRoles: [], status: 'deprecated' },
    rp: { ariaRoles: [], status: 'living-standard' },
    rt: { ariaRoles: [], status: 'living-standard' },
    rtc: { ariaRoles: [], status: 'deprecated' },
    ruby: { ariaRoles: [], status: 'living-standard' },
    s: { ariaRoles: [], status: 'living-standard' },
    samp: { ariaRoles: ['generic'], status: 'living-standard' },
    script: { ariaRoles: [], status: 'living-standard' },
    search: { ariaRoles: ['search'], status: 'living-standard' },
    section: { ariaRoles: ['region', 'generic'], status: 'living-standard' },
    select: { ariaRoles: ['combobox', 'listbox'], status: 'living-standard' },
    slot: { ariaRoles: [], status: 'living-standard' },
    small: { ariaRoles: ['generic'], status: 'living-standard' },
    span: { ariaRoles: ['generic'], status: 'living-standard' },
    strike: { ariaRoles: [], status: 'deprecated' },
    strong: { ariaRoles: ['strong'], status: 'living-standard' },
    style: { ariaRoles: [], status: 'living-standard' },
    sub: { ariaRoles: ['subscript'], status: 'living-standard' },
    summary: { ariaRoles: [], status: 'living-standard' },
    sup: { ariaRoles: ['superscript'], status: 'living-standard' },
    table: { ariaRoles: ['table'], status: 'living-standard' },
    tbody: { ariaRoles: ['rowgroup'], status: 'living-standard' },
    td: { ariaRoles: ['cell'], status: 'living-standard' },
    template: { ariaRoles: [], status: 'living-standard' },
    textarea: { ariaRoles: ['textbox'], status: 'living-standard' },
    tfoot: { ariaRoles: ['rowgroup'], status: 'living-standard' },
    th: { ariaRoles: ['columnheader', 'rowheader'], status: 'living-standard' },
    thead: { ariaRoles: ['rowgroup'], status: 'living-standard' },
    time: { ariaRoles: ['time'], status: 'living-standard' },
    title: { ariaRoles: [], status: 'living-standard' },
    tr: { ariaRoles: ['row'], status: 'living-standard' },
    tt: { ariaRoles: ['generic'], status: 'deprecated' },
    u: { ariaRoles: ['generic'], status: 'living-standard' },
    ul: { ariaRoles: ['list'], status: 'living-standard' },
    var: { ariaRoles: [], status: 'living-standard' },
    video: { ariaRoles: [], status: 'living-standard' },
    xmp: { ariaRoles: ['generic'], status: 'deprecated' },
  },
  ...{
    applet: { ariaRoles: ['generic'], status: 'deprecated' },
    basefont: { ariaRoles: [], status: 'deprecated' },
    bgsound: { ariaRoles: [], status: 'deprecated' },
    blink: { ariaRoles: ['generic'], status: 'deprecated' },
    isindex: { ariaRoles: [], status: 'deprecated' },
    keygen: { ariaRoles: [], status: 'deprecated' },
    listing: { ariaRoles: [], status: 'deprecated' },
    menuitem: { ariaRoles: ['menuitem'], status: 'deprecated' },
    multicol: { ariaRoles: [], status: 'deprecated' },
    nextid: { ariaRoles: [], status: 'deprecated' },
    spacer: { ariaRoles: [], status: 'deprecated' },
  },
} as const
